<a href="https://colab.research.google.com/github/dareoyeleke/python_scripting/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Intermediate NumPy — Indexing, Slicing & Broadcasting**

This notebook builds on NumPy foundations with more advanced data manipulation techniques.

You'll explore:

- Indexing and slicing multidimensional arrays  
- Broadcasting rules and behavior  
- Using universal functions (ufuncs)  
- Performing efficient element-wise computations  

These tools let you work fluently with complex numerical datasets.


In [ ]:
import numpy as np
import random as rand
'''
  To find the shape of a numpy array
'''

zero_array = np.array((10))
zero_array
print("Dimension of array is", zero_array.ndim, "& shape of array is", zero_array.shape) # the shape prints out an empty tuple because it's a zero dim array

# to do the same for a zero dimensional array
one_array = np.array([11, 12, 13, 14])
print("Dimension of array one_array is", one_array.ndim, "and the shape of the array is", one_array.shape)

# to do the same for a two dim array, the shape just tells how the matrix is arranged in the array
two_array = np.array(([2,3,3], [3,3,3], [2,2,2]))
print("Dimension of array in two_array is", two_array.ndim, "and the shape of the array is", two_array.shape)

'''
  to do the same for a three dim array amd also find the shape, careful of the number and type of brackets you put the values in. The shape of the array tells you what is in the array, i.e for this 3 dim array,
  (2,2,2) the 1st two is the number of 2d arrays, the 2nd 2 is the number of 2d rows, and the 3rd two is the number of 2d columns
'''
three_array = np.array([[[2,2], [3,3]], [[4,4], [5,5]]])
print ("Dimension of three_array is", three_array.ndim, "and the shape of the array is", three_array.shape)

'''
to do the same for a 4 dim array and tell its shape. Here the shape is (1,3,2,2) 1 is the number of 3d arrays, 3 means in that one 3d array, you have 3 2-d arrays made up of 2 rows(the 3rd number '2'),
and 2 columns (the 4th number 2)
'''
four_array = np.array([[[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]]]])
print('The dimension of four_array is', four_array.ndim, "and the shape is", four_array.shape)

Dimension of array is 0 & shape of array is ()
Dimension of array one_array is 1 and the shape of the array is (4,)
Dimension of array in two_array is 2 and the shape of the array is (3, 3)
Dimension of three_array is 3 and the shape of the array is (2, 2, 2)
The dimension of four_array is 4 and the shape is (1, 3, 2, 2)


In [ ]:
'''
  RESHAPING AN ARRAY. First the number of elements in a dimension is the shape. Reshaping is done with the object.reshape() method in python. Reshaping allows you to edit the number of elements in a dimension.
  You edit the number of dimensions in an array, inflate i.e from 1 --> 3 dims, or flatten, i.e from 3 --> 1 dims
'''

# here we'll be reshaping the one_array from above
print("one_array currently has", one_array.ndim, "Dimension")

"""
  to reshape the dimensions in the array, howver the matrix you have has to match the number of values in the array to be reshaped, i.e one_array has 4 elements, you cannot reshape into a (2,3),
  array as you need 2 rows of 3 columns, i.e 2*3 values i.e 6 values, however, (2,2) array works since it has 4 values for "2*2, i.e 4 values" for the array, also the array seems to reshape in order,
  i.e first 2 values go in 1st dim and next 2 values go in next dim
"""
one_to_two_array = one_array.reshape(2,2)
one_to_two_array

one_array currently has 1 Dimension


array([[11, 12],
       [13, 14]])

In [ ]:
# to test reshaping a (6,) shape array into (2,3) and (3,2) with .reshape() method
new_one_array = np.array ([10,11,12,13,15,18])
new_one_array

new_one_to_two = new_one_array.reshape(2,3)
print("The new_one_to_two array is a (2,3) shape as thus\n",  new_one_to_two)

# To reshape the new_one_to_two array from a (2,3) into a (3,2) array

modified_one_to_two_array = new_one_to_two.reshape(3,2)
print("The modified_one_to_two_array is went from a (2,3) to a (3,2) shape as thus \n", modified_one_to_two_array)



The new_one_to_two array is a (2,3) shape as thus
 [[10 11 12]
 [13 15 18]]
The modified_one_to_two_array is went from a (2,3) to a (3,2) shape as thus 
 [[10 11]
 [12 13]
 [15 18]]


In [ ]:
'''
  In this case we flatten the array from a 3-dim array, the three_array from above into a one dim or two dim array
'''
print("The three_array is currently a 3-dim array as shown\n", three_array)

# to flatten to a one or 2 dim, i.e chnage it from a (2,2,2) array to a (2,4), (4,2), or a (8,) array, we do so below, here we do so from a 3 to a 2 which is (2,4) first, and then a (4,2)
three_to_two_flat = three_array.reshape(2,4)
print("\n")
print("I have reshaped the three_array from (2,2,2) to (2,4) by flattening it as thus \n", three_to_two_flat)
print("\n", "\n")

# this time we'll change it to a (4,2), printing out the three_arrayy first to show it's shape is still a (2,2,2), and then reshape it to a (4,2)
print("The three array is still a (2,2,2) as shown thus \n", three_array)
print("\n")
modified_one_to_two_array_42 = three_array.reshape(4,2)
print("\n")
print("I have now modified the (2,2,2) array into a (4,2) array as thus \n", modified_one_to_two_array_42)
print("\n", "\n")

# now to change the three_array from (2,2,2) into a one dim array of (8,), we first print the array to show it's (2,2,2) and then flatten it to (8,)
print("The three_array, before flattening to a 1-dim is still a (2,2,2) as thus \n", three_array)
print("\n")
three_array_to_one = three_array.reshape(8) # i used (8,) to flatten, since (8,) is the new shape, but alternatively you can use (-1) to flatten to a one dim array. I prefer using the new shape though
print("\n")
print("The three_array shape (2,2,2) is now flattened to a 1-dim shape (8,) as thus \n", three_array_to_one)

### YYYYYUUUPPPPP!!!!!! it all worked!!!!

The three_array is currently a 3-dim array as shown
 [[[2 2]
  [3 3]]

 [[4 4]
  [5 5]]]


I have reshaped the three_array from (2,2,2) to (2,4) by flattening it as thus 
 [[2 2 3 3]
 [4 4 5 5]]

 

The three array is still a (2,2,2) as shown thus 
 [[[2 2]
  [3 3]]

 [[4 4]
  [5 5]]]




I have now modified the (2,2,2) array into a (4,2) array as thus 
 [[2 2]
 [3 3]
 [4 4]
 [5 5]]

 

The three_array, before flattening to a 1-dim is still a (2,2,2) as thus 
 [[[2 2]
  [3 3]]

 [[4 4]
  [5 5]]]




The three_array shape (2,2,2) is now flattened to a 1-dim shape (8,) as thus 
 [2 2 3 3 4 4 5 5]


In [ ]:
'''
  Here I tried to print out values using for loop, with rand.randint, for a 4 dim array, it worked but it assigned the same patterns to all arrays, however, running the same loop for each array individually,
  printed different values for each array, but the same values for all the elements in an array.
'''
new_four_array = np.zeros([4,4,4,4])
new_four_array

for matrix in new_four_array[0]:
  if np.all(matrix == 0):
    matrix += rand.randint(0,50)
    print(matrix)
  else:
    print("nothing")

for matrix in new_four_array[1]:
  if np.all(matrix == 0):
    matrix += rand.randint(0,50)
    print(matrix)
  else:
    print("nothing")

for matrix in new_four_array[2]:
  if np.all(matrix == 0):
    matrix += rand.randint(0,50)
    print(matrix)
  else:
    print("nothing")


for matrix in new_four_array[3]:
  if np.all(matrix == 0):
    matrix += rand.randint(0,50)
    print(matrix)
  else:
    print("nothing")

[[18. 18. 18. 18.]
 [18. 18. 18. 18.]
 [18. 18. 18. 18.]
 [18. 18. 18. 18.]]
[[36. 36. 36. 36.]
 [36. 36. 36. 36.]
 [36. 36. 36. 36.]
 [36. 36. 36. 36.]]
[[47. 47. 47. 47.]
 [47. 47. 47. 47.]
 [47. 47. 47. 47.]
 [47. 47. 47. 47.]]
[[20. 20. 20. 20.]
 [20. 20. 20. 20.]
 [20. 20. 20. 20.]
 [20. 20. 20. 20.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[42. 42. 42. 42.]
 [42. 42. 42. 42.]
 [42. 42. 42. 42.]
 [42. 42. 42. 42.]]
[[11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]]
[[25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]]
[[28. 28. 28. 28.]
 [28. 28. 28. 28.]
 [28. 28. 28. 28.]
 [28. 28. 28. 28.]]
[[24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]]
[[30. 30. 30. 30.]
 [30. 30. 30. 30.]
 [30. 30. 30. 30.]
 [30. 30. 30. 30.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 

In [ ]:
# Here the video teaches me how to iterate, I hope i can at least learn how to assign different values. Iterative statements for 0-2 dim arrays. NM, it was just to print out the elements in the array. In this case it was for a 1-dim

iter_zero_array = np.array([5, 10, 15, 20, 25, 30])

for ele in iter_zero_array:
  print(ele)
print(" \n")

# In this case we will try to iterate a 2-dim array, we will use the two-array from above and first print to confirm the dimensions in the array

print("To work on a 2-dim array, I will be printing out a 2-dim array and the dim number as well for two_array as thus\n", two_array, "\nThe Dimension number is", two_array.ndim ) # now we iterate two_array

print("\n")
two_array

print("\n")

for elem in two_array:
  print(elem) # the array for a 2-dim prints out in the form of the matrix as well, not like the 1-dim that just prints out numbers, below we wil have a 3-dim array
print("\n")


print("To work on a 3-dim array, I will be printing out a 3-dim array and the dim number as well for three_array as thus\n", three_array, "\nThe Dimension number is", three_array.ndim, "\n" ) # now we iterate three_array

for eleme in three_array:
  print(eleme) # just like the 2-dim array, the 3-dim array




5
10
15
20
25
30
 

To work on a 2-dim array, I will be printing out a 2-dim array and the dim number as well for two_array as thus
 [[2 3 3]
 [3 3 3]
 [2 2 2]] 
The Dimension number is 2




[2 3 3]
[3 3 3]
[2 2 2]


To work on a 3-dim array, I will be printing out a 3-dim array and the dim number as well for three_array as thus
 [[[2 2]
  [3 3]]

 [[4 4]
  [5 5]]] 
The Dimension number is 3 

[[2 2]
 [3 3]]
[[4 4]
 [5 5]]
