<a href="https://colab.research.google.com/github/dareoyeleke/python_scripting/blob/main/Numpy_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# create a list of 1,000,000 salaries ranging from 50,000 to 150,000
import random

# creates a range of values between 2 defined numbers passed as arguments, using list comprehension and loops we use random.randint() to create 1,000,000 values btwn 50,000 and 100,000
salary_list = [random.randint(50000, 100000) for no in range (10000000)]

In [ ]:
import statistics

In [ ]:
%%timeit
'''
  %%timeit is used to get the avg time for how long it would take to run the fucntion below, the results show 260 ms +- 7.83 ms per loop (mean +- std dev of 7 runs, 1 loop each) for 1 million values.
  The import stats was shifted abovepreventing that from being taken into consideration in the time below. It took 2.89 s +- 475 ms per loop(7 runs, 1 loop each) for 10 mill values
'''
symbol = "$"
f'{symbol}{statistics.mean(salary_list)}'

3.75 s ± 905 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
import numpy as np

In [ ]:
# this took 74.2 ms +- 19.7 ms per loop for 7 runs, 10 loops each for 1 million values. For 10 million values, it took 733 ms +- 1996 ms per loop(7 runs, 1 loop)
%%timeit
np.mean(salary_list)

736 ms ± 86.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# create a numpy array by calling a tuple, nd array means non-dimensional array
n = np.array((1,2,3))
n
type(n)

numpy.ndarray

In [ ]:
# create a numpy array by passing a list

l = np.array([4,5,6])
l
type(l)

# to print dimension type, use object.ndim i.e for l, l.ndim
print("Dimensions =", l.ndim)


Dimensions = 1


In [ ]:
# create a 2 dimensional array with a list, notice the double square brackets

two = np.array ([[7,8],[9,10]])
two
print("List dimemnsion no is ", two.ndim)

# create a 2d array with a tuple, notice the triple brackets
twotup = np.array(((7,8),(9,10)))
twotup
print("Tuple Dimensions are", twotup.ndim, "in Number")

# trying to access values in an array, i personally use two square brackets as opposed to seperating the array index and value index by a comma.
two[1,0]

List dimemnsion no is  2
Tuple Dimensions are 2 in Number


np.int64(9)

In [ ]:
# initialize an array with the .zeros() method, here the 2 means two rows, and the three means 3 columns, almost like a 2 x 3 matrix, zeros_array prints as a non dimensionsal array type, with 2 dimensions
zeros_array = np.zeros([2,3])
zeros_array
type(zeros_array)
zeros_array.ndim

2

In [ ]:
# creating a 4 x 4 array, remember always double brack or square brack inside brack when arraying
fourx_array = np.zeros([4,4])
fourx_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# just messing around with indexing an array in a 1-d array
string_array = np.array(("dare","yemo", "tims", "wole", "OP"))
string_array
string_array[0] = "Tims"
string_array[1] = "Yemo"
string_array[2] = "OP"
string_array[3] = "Wole"
string_array[4] = "Dare"
string_array

# you can also access values by indexing with index like usual i.e
print ("The Oyeleke first born is", string_array [0])

The Oyeleke first born is Tims


In [ ]:
# when i chnaged even one value to a string, and tried to get the type for individual indexes, it always returned a string
strings_array = np.array([1, 15, 2, 4])
type(strings_array[1])

numpy.int64

In [ ]:
# to get the data type for values in an array, without having to index use object.dtyp, with just numbers it printed int64, with one str and 3 numbers, it printed <U21
rand_array = np.array([10, 20, 30])
rand_array
rand_array.dtype

#repeating the .dtype attribute for string data in an array <U4 and <U21 basically mean at most 4 and 21 max characters per value allowed as strings
rand2_array = np.array(["Timi", "Yemo", "Ope", 22])
rand2_array.dtype

dtype('<U21')

In [ ]:
# assigning data type and value limit in an array, in this case S = string and 5 is max no of values, prints out S5 when dtype is called
leke_kids = np.array(['Tims', 'Yemo', 'OP', 'Wole', 'Dare'], dtype = 'S5')
leke_kids.dtype

dtype('S5')

In [ ]:
# changing data types for an array with astype() method
rand_array = np.array([10, 20, 30])

# dtype here is printed as 'int64'
rand_array.dtype

# using astype to convert it to string, here it's not yet converted, just printed out as a string, as the data type still prints as int64 when called
rand_array.astype('S')
rand_array.dtype

# to convert it into a string, you would have to store it in an object that holds the string method with it as below, i.e rand_array_string.dtype, now prints as string, "i" also converts to integer
rand_array_string = rand_array.astype('S')
rand_array_string.dtype

dtype('S21')

In [ ]:
test_matrix = np.zeros([4,4], 'f')

# prints a 4x4 matrix as an array
test_matrix

# trying to apply indices to a matrix array, the numbers, it worked, i replaced an empyty array test_matrix[0] which was ([0., 0., 0., 0.]) with ([0., 1., 2., 3.]), the dots arent necessary, they print by default
test_matrix[0] = np.array([0., 1., 2., 3.])
test_matrix[1] = np.array([4., 5., 6., 7.])
test_matrix[2] = np.array([8., 9., 10., 11.])
test_matrix[3] = np.array([12, 13., 14., 15.])

# using double indices to first identify the index of the matrix, and the index of the value in the array, so here 3 is the  index value 3 in the matrix, and 2 is the index value 2 in the 3rd matrix called before it
test_matrix[3][2]

# to test the data format after the type was
test_matrix.dtype

'''
  to change and test the change of matrix positions in an array, when the test_matrix = np.zeros ([matrix], "data_type"), when the data type is i, whatever number you change it to, i.e a decimal converts to a whole number, but f(float)
  keeps the decimal.  Also to assign values to a
'''
test_matrix[3][3] =  15.5
test_matrix[3] = ([15, 16, 17, 18])
test_matrix.ndim

2

In [ ]:
second_matrix = np.zeros([4,4])
second_matrix

'''
  trying to assign values to a 4x4 matrix without using indices, using random.randit with list comprehension to print out random 16 values. So generating 16 random values using rand.randint and a for range loop and storing the 16 values in an object.
  then assigning the matrix to the object with the values doesn't work as the matrix object just becomes the value list as opposed to converting the list to matrixes.Using indices to assign the whole matrix to the value list doesn't work either, like
  'matrix[0:4] = value list of 16 objects' as the list doesn't automatically assign the list to the required values for every index. i.e it cannot broadcast input array from rand.randint into the shape [0:4] of the matrix.
  however using "matrix [0:4] = [rand.randint(0,20)for no in range(4)] works as the range(4) is the number of values required, unfortunately it generates the same values for all matrix dimensions
'''
import random as rand

second_list = [rand.randint(5, 15)for no in range (16)]
second_matrix [0:4] += [rand.randint(0,20) for no in range(4)]
second_matrix

array([[ 8., 18.,  9., 19.],
       [ 8., 18.,  9., 19.],
       [ 8., 18.,  9., 19.],
       [ 8., 18.,  9., 19.]])

In [ ]:
'''
  Here there are 3 figures in the np.zeros(), the first figure signifies the number of matrixes i.e 3, the next two are the layout, i.e 3 rows(the first number), and 3 columns(the second number).
  Calling the matrices, rows and values work the same using index, the first [] for matrix number, the second one for the row and the 3rd for the value position as below
'''
three_matrix = np.zeros([3,3,3])
three_matrix # prints out the matrix

# while the values are all zeros, printing out the values in a matrix work the same with indices, here i also assigned values to every element of the matrix, in this case, all integers
three_matrix[0][0] = (1,2,3)
three_matrix[0][1] = (4,5,6)
three_matrix[0][2] = (7,8,9)
three_matrix

three_matrix[1][0] = (10,11,12)
three_matrix[1][1] = (13,14,15)
three_matrix[1][2] = (16,17,18)
three_matrix

three_matrix[2][0] = (19,20,21)
three_matrix[2][1] = (22,23,24)
three_matrix[2][2] = (25,26,27)
three_matrix

'''
  here i called the three_matrix [1:][1], however, as opposed to [1][1] when i added another index, [1:][1], prints out the instance from [1:][1] as [0], and the next instance as [1], calling [1:][0] as the whole of
  three_matrix [1], and [1:][1] as the entirety of three_matrix[2], not to be confused with three_matrix[1][1], which is just the three values assigned to it above.
'''
three_matrix[1][1]






array([13., 14., 15.])

In [ ]:

'''
  Here there are 4 values, the first 2 are multiplied to give the value of the number of matrices, i.e 3*3, 9 matrixes, the next 2 values are 2 rows, by 3 colums. Calling the matrices,
  rows and values work the same using index,the first [] for matrix number, the second one for the row and the 3rd for the value position as below. Actually the first values of [3,3] in
  [3,3,2,3] means 3 sets of 3 matrices, with the next values [2,3] meaning 2 rows with 3 columns. As opposed to manual assignment, i used a loop statement, however, I wasnt privy of the np.all function,
  which reads every element in a matrix, and then that way we can decide the action to take on every value
'''
four_matrix = np.zeros([3,3,2,3])

four_matrix

for sub_matrix in four_matrix:
  # Correcting the syntax: use '==' for comparison.
  # The comparison `sub_matrix == ([0,0,0,0])` was problematic because `sub_matrix`
  # is a (3,2,3) numpy array, not a list of 4 elements. This checks if all elements in sub_matrix are 0.
  # np.all checks if all the elements of a matrix equate to something
  if np.all(sub_matrix == 0):
    sub_matrix += rand.randint(0,55) # Modify the sub_matrix in-place
    print(sub_matrix) # Then print the modified sub_matrix
  else:
    print("nothing")


In [ ]:
four_matrix.ndim


4

In [ ]:
for sub_matrix in four_matrix:
  # Correcting the syntax: use '==' for comparison.
  # The comparison `sub_matrix == ([0,0,0,0])` was problematic because `sub_matrix`
  # is a (3,2,3) numpy array, not a list of 4 elements. This checks if all elements in sub_matrix are 0.
  if np.all(sub_matrix == 0):
    random_integer_to_add = rand.randint(0,20)
    sub_matrix += random_integer_to_add # Modify the sub_matrix in-place
    print(sub_matrix) # Then print the modified sub_matrix
  else:
    print("nothing")