<a href="https://colab.research.google.com/github/dareoyeleke/python_scripting/blob/main/Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random as rand



In [ ]:
salary = np.zeros([4,4])
salary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# using a random data set to create random values as salaries for employees working in a non-profit law health center
for no in salary:
  if np.all(no == 0):
    no += rand.randint(50000, 150000)
    print(no)
  else:
    print("nothing")

[77575. 77575. 77575. 77575.]
[54989. 54989. 54989. 54989.]
[129320. 129320. 129320. 129320.]
[120255. 120255. 120255. 120255.]


In [ ]:
# assigning the random salaries to an object to hold these specific values and showing that they are in $ USD
base_salary = np.copy(salary)
base_salary
print ("Salary in $ USD before deduction is\n", base_salary)

Salary in $ USD before deduction is
 [[ 77575.  77575.  77575.  77575.]
 [ 54989.  54989.  54989.  54989.]
 [129320. 129320. 129320. 129320.]
 [120255. 120255. 120255. 120255.]]


In [ ]:
# using a loop function, with np.all(), and conditions to iterate the deductions for salaries in a certain range
for no in base_salary:
  if np.all((no > 50000) & (no < 100000)):
    print ("Salary after 15% deduction in $ USD is", no * 0.85)
  elif np.all(no > 100000):
    print ("Salary after 25% deduction is $ USD is", no * .75 )

Salary after 15% deduction in $ USD is [65938.75 65938.75 65938.75 65938.75]
Salary after 15% deduction in $ USD is [46740.65 46740.65 46740.65 46740.65]
Salary after 25% deduction is $ USD is [96990. 96990. 96990. 96990.]
Salary after 25% deduction is $ USD is [90191.25 90191.25 90191.25 90191.25]


In [ ]:
'''
Since every one got bonuses for christmas, employees making less than $75000 after deductions all got bonuses of $1500 and employess making above $75000 got $750 in bonuses.
Let's compute that using the loop above and changing some elements of the loop
'''
deducted_salary = np.copy(base_salary)

for i, no in base_salary:
  if np.all((no > 50000) & (no < 100000)):
    print ("Salary after 15% deduction in $ USD is", no * 0.85)
  elif np.all(no > 100000):
    print ("Salary after 25% deduction is $ USD is", no * .75 )



In [ ]:
'''
To actually store the results in an object, we create a copy of the base_salary and store it in an object called deducted_salary, and then loop through deducted_salary and base_salary with an enumerate function,
and 2 loop variables i and no, attaching i as the loop variable for deducted_salary[i], after the if and elif statement and then pasing the return statements through the deducted_salary[i]
'''
deducted_salary = np.copy(base_salary)

# Loop through the base_salary with index to update the new array
for i, no in enumerate(base_salary):
  if np.all((no > 50000) & (no < 100000)):
    deducted_salary[i] = no * 0.85
  elif np.all(no > 100000):
    deducted_salary[i] = no * .75

print("Salaries after deductions in $ USD:\n", deducted_salary)

Salaries after deductions in $ USD:
 [[65938.75 65938.75 65938.75 65938.75]
 [46740.65 46740.65 46740.65 46740.65]
 [96990.   96990.   96990.   96990.  ]
 [90191.25 90191.25 90191.25 90191.25]]


In [ ]:
# Repeating the steps above, but this time using deducted_salary as the main loop object, and making a copy, storing it in an object and attaching another loop variable on it before using enumerate to loop through both
salary_bonus = np.copy(deducted_salary)

'''
  Scalar broadcasting - Loop through the base_salary with index to update the new array. Basically with enumerate, if no < 75,000 in deduction_ salary , it prints an instance of that no added to 1500 for salary_bonus[i],
  where [i] becomes every instance of a number in salary_bonus, and then if no > 75000 in deduction_salary, salary_bonus[i] prints out a value for [i] assigning it to the conditions in the if statement before it
'''
for i, no in enumerate(deducted_salary):
  if np.all(no < 75000):
    salary_bonus[i] = no + 1500
  elif np.all(no > 75000):
    salary_bonus[i] = no + 750

print('The full salary after deductions and inputing christmas salaries in $ USD are\n',salary_bonus)

The full salary after deductions and inputing christmas salaries in $ USD are
 [[67438.75 67438.75 67438.75 67438.75]
 [48240.65 48240.65 48240.65 48240.65]
 [97740.   97740.   97740.   97740.  ]
 [90941.25 90941.25 90941.25 90941.25]]


In [ ]:
for i, no in enumerate(deducted_salary):
  if np.all(no < 75000):
    salary_bonus[i] = "$" + str(no + 1500)
  elif np.all(no > 75000):
    salary_bonus[i] = "$" + str(no + 750)

To format the numbers in `salary_bonus` with a dollar sign and commas, you can iterate through the array and use an f-string or `str.format()` to apply the desired formatting to each number before printing.

In [ ]:
print('The full salary after deductions and inputing christmas salaries in $ USD are:')
for row in salary_bonus:
    formatted_row = [f"${val:,.2f}" for val in row]
    print(formatted_row)